version: '3.6'
services:
### Factorio Server ###
  server:
    image: jwilford/factorio
    ports:
      - 34197:34197/udp
    secrets:
      - map-gen-settings.json       # The map generation settings
      - map-settings.json           # The map difficulty settings
      - server-settings.json        # The server settings
    volumes:
      - factorio-saves:/saves/
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        
secrets:
  map-gen-settings.json:
    external: true
    name: factorio-map-gen-settings.json
  map-settings.json:
    external: true
    name: factorio-map-settings.json
  server-settings.json:
    external: true
    name: factorio-server-settings.json

volumes:
  factorio-saves:
    external: true